### ISSUE TITLE
Opening multiple VS Code windows causes connection to close

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/plugin-vscode#166]
**Description:**
When two VS Code windows are open the connection get closed in both. And didn't recover until I disabled the extension in one workspace and restarted the other

```
Auto detecting Ballerina home.
Plugin version: 2.0.0
Ballerina version: Swan Lake Preview 9 SNAPSHOT
Using Ballerina CLI command 'bal' for Language server.
/usr/bin/bal: line 92: 150692 Killed                  $BALLERINA_HOME/bin/./bal "$@"
[Info  - 2:21:26 PM] Connection to server got closed. Server will restart.
/usr/bin/bal: line 92: 151350 Killed                  $BALLERINA_HOME/bin/./bal "$@"
[Info  - 2:21:27 PM] Connection to server got closed. Server will restart.
[Error - 2:21:32 PM] Server initialization failed.
Error: Connection is closed.
	at G (/home/chiran/.vscode/extensions/ballerina.ballerina-2.0.0-Alpha-SNAPSHOT/dist/extension.js:1:18779)
	at Object.onNotification (/home/chiran/.vscode/extensions/ballerina.ballerina-2.0.0-Alpha-SNAPSHOT/dist/extension.js:1:19609)
	at Object.onDiagnostics (/home/chiran/.vscode/extensions/ballerina.ballerina-2.0.0-Alpha-SNAPSHOT/dist/extension.js:1:67739)
	at /home/chiran/.vscode/extensions/ballerina.ballerina-2.0.0-Alpha-SNAPSHOT/dist/extension.js:1:63231
[Error - 2:21:33 PM] Server initialization failed.
Error: Connection got disposed.
	at Object.dispose (/home/chiran/.vscode/extensions/ballerina.ballerina-2.0.0-Alpha-SNAPSHOT/dist/extension.js:1:21204)
	at Object.dispose (/home/chiran/.vscode/extensions/ballerina.ballerina-2.0.0-Alpha-SNAPSHOT/dist/extension.js:1:67809)
	at /home/chiran/.vscode/extensions/ballerina.ballerina-2.0.0-Alpha-SNAPSHOT/dist/extension.js:1:64759
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
VS Code 1.52.1
Ubuntu 20.04

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
We were able to replicate the issue when there're multiple debug adapter terminate requests happen in a single VSCode environment.
<img width="1255" alt="Screenshot 2021-02-15 at 18 53 20" src="https://user-images.githubusercontent.com/5234623/107953108-a5bd9080-6fc0-11eb-9ec2-ce41037b41d3.png">

As per the JSON-RCP implementation of VSCode and LS communication, the VSCode keeps a one-to-one mapping between the LS and the client connection. If LS stops, the client involves in restarting the LS for seamless communication. However, there are some scenarios where the client cannot restore the connection when the LS is consecutively and manually killed by another process. 

The previous Ballerina Debug Adapter implementation had been killing the LS connection at each **terminateRequest**, hence caused the mentioned issue. Due to the auto-recovery nature of the underline VSCode-LS communication, this issue hasn't been noticed unless there're a significant number of debugging client terminate requests. The new debug adapter [implementation](https://github.com/ballerina-platform/ballerina-lang/pull/28549/files#diff-a287f8c99e6e8f9903e0fe5ef0da07d024b77b32edfbc169366696ebbd1fbb94R523) (comes with SL Alpha2) has fixed this issue of killing LS instances of other VSCode instances.
