### ISSUE TITLE
VSCode does not show JAVA_HOME undefined error on Arch Linux

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/plugin-vscode#61]
It does not show startup error when plugin is activated.

**Comment by MomchilKolev** [comment]
![image](https://user-images.githubusercontent.com/26323192/99143415-ceeb1f80-2665-11eb-84ac-937b3e35e532.png)

Which is strange, since:

![image](https://user-images.githubusercontent.com/26323192/99143422-f346fc00-2665-11eb-9900-c1eec2022fd0.png)

and

![image](https://user-images.githubusercontent.com/26323192/99143460-5fc1fb00-2666-11eb-83cd-cf7fea60744c.png)

![image](https://user-images.githubusercontent.com/26323192/99143468-6e101700-2666-11eb-8da1-f552bdf9b37c.png)

**Comment by prabushi** [comment]
Extension initialization has been fixed with Swan Lake release. Please reopen the issue if you still get the error.
